### ISSUE TITLE
Error when viewing settings page

### ISSUE THREAD

**Issue by chrisburton** [jrc9designstudio/google-analytics-v2-hub#4]
I received an error upon installing and visiting the settings page. Specifically `width:50` in `settings.yaml`. The cause for this error is a missing space. 

**source:** `/site/addons/GoogleAnalytics/settings.yaml`

**Error:**

```yaml
link_id:
    type: toggle
    width:50
```

**Fix:**
```yaml
link_id:
    type: toggle
    width: 50
```
